name: build-test-lint
on: [push, pull_request]
jobs:
  build:
    name: build
    strategy:
      matrix:
        go-version: [1.18.x]
        goarch: [amd64]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Go matrix
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build
        env:
          GOARCH: ${{ matrix.goarch }}
          GOOS: ${{ matrix.goos }}
        run: make build

  test:
    runs-on: ubuntu-latest
    needs: build
    name: test
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Install hwdata
        run: sudo apt-get install hwdata -y

      - name: Go test
        run: make test

  test-coverage:
    runs-on: ubuntu-latest
    needs: build
    name: test-coverage
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x

      - uses: actions/checkout@v2

      - name: Install hwdata
        run: sudo apt-get install hwdata -y

      - name: Go test with coverage
        run: make test-coverage

  golangci:
    name: Golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.46.2

  hadolint:
    runs-on: ubuntu-latest
    name: Hadolint
    steps:
    - uses: actions/checkout@v2
    - uses: brpaz/hadolint-action@v1.5.0
      name: Run Hadolint
      with:
       dockerfile: ./Dockerfile
       ignore: DL3018 # DL3018: GH issue 368

  go-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18.x

    # if this fails, run go mod tidy
    - name: Check if module files are consistent with code
      run: go mod tidy && git diff --exit-code

    # if this fails, run go mod vendor
    - name: Check if vendor directory is consistent with go modules
      run: go mod vendor && git diff --exit-code
